# Для активации Yarn Berry используйте yarn set version berry
yarnPath: .yarn/releases/yarn-4.5.0.cjs
# nodeLinker: node-modules # Указывает Yarn использовать классический способ установки с node_modules вместо Plug'n'Play